language: node_js

sudo: false

node_js:
  - "6.9"

cache:
  apt: true
  directories:
    - node_modules


addons:
  ssh_known_hosts: github.com


script:
  - node -v

branches:
  only:
    - master

before_intall:
  - openssl aes-256-cbc -K $encrypted_c66859c4f6bf_key -iv $encrypted_c66859c4f6bf_iv -in id_rsa.enc -out id_rsa -d
